<script setup lang="ts">
import { onMounted, ref } from 'vue';
type Skill = { id: string; categoryId: string; name: string; currentLevel: number; targetLevel: number; criteria: string; notes: string }; type Category = { id: string; name: string; isActive: boolean };
const items = ref<Skill[]>([]); const categories = ref<Category[]>([]); const selected = ref<Skill | null>(null); const editing = ref(false); const message = ref(''); const form = ref({ categoryId: '', name: '', currentLevel: 1, targetLevel: 1, criteria: '', notes: '' });
async function load() { const [skillsResponse, settingsResponse] = await Promise.all([fetch('/api/skills'), fetch('/api/skill-settings')]); const skills = await skillsResponse.json() as { items?: Skill[]; message?: string }; const settings = await settingsResponse.json() as { categories?: Category[] }; items.value = skills.items ?? []; categories.value = (settings.categories ?? []).filter(({ isActive }) => isActive); message.value = skillsResponse.ok ? '' : skills.message ?? '一覧を取得できませんでした。'; }
function startCreate() { selected.value = null; editing.value = true; form.value = { categoryId: categories.value[0]?.id ?? '', name: '', currentLevel: 1, targetLevel: 1, criteria: '', notes: '' }; }
function startEdit(skill: Skill) { selected.value = skill; editing.value = true; form.value = { ...skill }; }
async function save() { const response = await fetch(selected.value ? `/api/skills/${selected.value.id}` : '/api/skills', { method: selected.value ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form.value) }); const body = await response.json() as { message?: string }; if (!response.ok) { message.value = body.message ?? '保存できませんでした。'; return; } editing.value = false; selected.value = null; await load(); }
async function archive(skill: Skill) { if (!confirm(`「${skill.name}」をアーカイブしますか？`)) return; const response = await fetch(`/api/skills/${skill.id}`, { method: 'DELETE' }); if (!response.ok) { message.value = 'アーカイブできませんでした。'; return; } selected.value = null; await load(); }
onMounted(load);
</script>
<template><section><div class="view-heading"><div><p class="eyebrow">Skills</p><h1>スキル</h1></div><button class="primary-button compact" @click="startCreate">新規作成</button></div><p v-if="message" class="form-error" role="alert">{{ message }}</p><form v-if="editing" class="goal-form" @submit.prevent="save"><h2>{{ selected ? 'スキルを編集' : 'スキルを登録' }}</h2><label>スキル名<input v-model="form.name" maxlength="200" required /></label><label>分類<select v-model="form.categoryId" required><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.name }}</option></select></label><label>現在レベル<select v-model.number="form.currentLevel"><option v-for="level in 5" :key="level" :value="level">{{ level }}</option></select></label><label>目標レベル<select v-model.number="form.targetLevel"><option v-for="level in 5" :key="level" :value="level">{{ level }}</option></select></label><label>判定基準<textarea v-model="form.criteria" maxlength="2000" /></label><label>備考<textarea v-model="form.notes" maxlength="2000" /></label><div><button class="primary-button compact">保存</button><button class="text-button" type="button" @click="editing = false">キャンセル</button></div></form><div v-else-if="items.length" class="goal-grid"><article v-for="skill in items" :key="skill.id" class="goal-card" @click="selected = skill"><h2>{{ skill.name }}</h2><p>現在 {{ skill.currentLevel }} → 目標 {{ skill.targetLevel }}</p><button class="text-button" @click.stop="startEdit(skill)">編集</button><button class="text-button danger" @click.stop="archive(skill)">アーカイブ</button></article></div><section v-else-if="!editing" class="empty-state"><h2>スキルはまだありません</h2><p>「新規作成」から現在・目標レベルと判定基準を登録してください。</p></section><section v-if="selected && !editing" class="goal-detail"><h2>{{ selected.name }}</h2><p><strong>現在・目標:</strong> {{ selected.currentLevel }} → {{ selected.targetLevel }}</p><p><strong>判定基準:</strong> {{ selected.criteria || '未入力' }}</p><p><strong>備考:</strong> {{ selected.notes || '未入力' }}</p></section></section></template>
