<script setup lang="ts">
import { onMounted, ref } from 'vue';
type Category = { id: string; name: string; displayOrder: number; isActive: boolean }; type Level = { level: number; name: string; description: string };
const categories = ref<Category[]>([]); const levels = ref<Level[]>([]); const message = ref(''); const newName = ref('');
async function load() { const response = await fetch('/api/skill-settings'); const body = await response.json() as { categories?: Category[]; levels?: Level[]; message?: string }; categories.value = body.categories ?? []; levels.value = body.levels ?? []; message.value = response.ok ? '' : body.message ?? '設定を取得できませんでした。'; }
async function addCategory() { const response = await fetch('/api/skill-settings/categories', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: newName.value, displayOrder: categories.value.length + 1 }) }); const body = await response.json() as { message?: string }; if (!response.ok) { message.value = body.message ?? '分類を追加できませんでした。'; return; } newName.value = ''; await load(); }
async function saveCategory(category: Category) { const response = await fetch(`/api/skill-settings/categories/${category.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(category) }); if (!response.ok) message.value = '分類を更新できませんでした。'; else await load(); }
async function saveLevel(level: Level) { const response = await fetch(`/api/skill-settings/levels/${level.level}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(level) }); if (!response.ok) message.value = 'レベル定義を更新できませんでした。'; }
onMounted(load);
</script>
<template><section><p class="eyebrow">Settings</p><h1>スキル設定</h1><p v-if="message" class="form-error" role="alert">{{ message }}</p><section class="settings-panel"><h2>スキル分類</h2><form class="inline-form" @submit.prevent="addCategory"><input v-model="newName" maxlength="100" placeholder="新しい分類名" required /><button class="primary-button compact">追加</button></form><p v-if="!categories.length">分類はまだありません。</p><div v-for="category in categories" :key="category.id" class="setting-row"><input v-model="category.name" maxlength="100" /><input v-model.number="category.displayOrder" type="number" min="0" /><label><input v-model="category.isActive" type="checkbox" />有効</label><button class="text-button" @click="saveCategory(category)">保存</button></div></section><section class="settings-panel"><h2>レベル定義（1～5）</h2><div v-for="level in levels" :key="level.level" class="level-row"><strong>レベル {{ level.level }}</strong><input v-model="level.name" maxlength="100" /><textarea v-model="level.description" maxlength="500" /><button class="text-button" @click="saveLevel(level)">保存</button></div></section></section></template>
